python src/kge_nfm.py \
  --dataset yamanishi_08 \
  --data_root /kaggle/input/datasets/ngcaovn/kge-dti/data \
  --split warm_start_1_10 \
  --folds 10 \
  --device auto \
  --embedding-dim 400 \
  --kge-epochs 50 \
  --nfm-epochs 2000 \
  --kge-batch-size 1024 \
  --batch-size 20000 \
  --nfm-sparse-embedding-dim 50 \
  --nfm-lr 0.001 \
  --nfm-weight-decay 0.00001 \
  --nfm-hidden-units 128,128 \
  --nfm-patience 10 \
  --output-dir ./output/kge_nfm_torch
